baseurl = "/"
languageCode = "en-US"
title = "Jiman Hwang"

# Enable comments by entering your Disqus shortname
# Remove comments at hugo-sustain/layouts/partials/disqus.html to use
#disqusShortname = ""

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

pluralizelisttitles = "false"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Jiman Hwang"
  description = "Molehair"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "username"
  Email         = "email@example.com"
  Twitter       = "username"
  LinkedIn      = "username"
  Stackoverflow = "username"

## Main Menu
[[menu.main]]
  name = "activity"
  weight = 100
  identifier = "activity"
  url = "/activity/"
[[menu.main]]
  name = "computer science"
  identifier = "computer science"
  weight = 200
  url = "/computer science/"
[[menu.main]]
  name = "mathematics"
  identifier = "mathematics"
  weight = 300
  url = "/mathematics/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 400
  url = "/resume_public.pdf"
[[menu.main]]
  name = "CV"
  identifier = "CV"
  weight = 500
  url = "/cv_public.pdf"
[[menu.main]]
  name = "Git"
  identifier = "Git"
  weight = 600
  url = "https://github.com/molehair"
